PACKAGE_NAME="apple-ib-drv"
PACKAGE_VERSION="0.1"
BUILT_MODULE_NAME[0]="apple-ibridge"
DEST_MODULE_LOCATION[0]="/updates"
BUILT_MODULE_NAME[1]="apple-touchbar"
DEST_MODULE_LOCATION[1]="/updates"
MAKE[0]="make KVERSION=${kernelver}"
CLEAN="make clean KVERSION=${kernelver}"
AUTOINSTALL="yes"
